"""
gcode_generator.py
------------------
Converts optimised polylines (in mm coordinates) into G-code suitable for a
3D printer used as a 2D pen plotter.

Conventions:
  G21  — mm units
  G90  — absolute positioning
  G0   — rapid move (pen up travel)
  G1   — feed move (drawing stroke)
  Z5   — pen UP
  Z0   — pen DOWN
  No E-axis commands ever.
"""

from typing import List, Tuple

Point = Tuple[float, float]
Polyline = List[Point]


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def generate_gcode(
    polylines: List[Polyline],
    feed_rate: float = 3000.0,       # mm/min drawing speed
    travel_rate: float = 6000.0,     # mm/min pen-up travel speed
    pen_up_z: float = 5.0,           # mm — Z height when pen is raised
    pen_down_z: float = 0.0,         # mm — Z height when pen is on paper
    decimal_places: int = 3,
) -> str:
    """
    Generate a complete G-code program string from optimised polylines.

    Args:
        polylines     : list of polylines in mm coordinates (x, y)
        feed_rate     : drawing feed rate (mm/min)
        travel_rate   : rapid travel feed rate (mm/min)
        pen_up_z      : Z value for pen-up position
        pen_down_z    : Z value for pen-down (drawing) position
        decimal_places: coordinate rounding precision

    Returns:
        G-code as a single string.
    """
    dp = decimal_places
    lines: List[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "; ========================================================",
        "; G-code generated by Image Plotter",
        f"; Feed rate   : {feed_rate} mm/min",
        f"; Travel rate : {travel_rate} mm/min",
        f"; Pen up Z    : {pen_up_z} mm",
        f"; Pen down Z  : {pen_down_z} mm",
        "; ========================================================",
        "",
        "G21          ; Set units to millimetres",
        "G90          ; Absolute positioning",
        f"G0 Z{pen_up_z:.{dp}f}   ; Lift pen before starting",
        "G0 X0 Y0     ; Move to origin",
        "",
    ]

    pen_is_up = True

    for path_idx, poly in enumerate(polylines):
        if len(poly) < 2:
            continue

        start = poly[0]
        lines.append(f"; --- Path {path_idx + 1} ---")

        # Travel to path start (pen up)
        if not pen_is_up:
            lines.append(f"G0 Z{pen_up_z:.{dp}f}    ; Pen UP")
            pen_is_up = True
        lines.append(
            f"G0 X{start[0]:.{dp}f} Y{start[1]:.{dp}f} F{travel_rate:.0f}  ; Travel"
        )

        # Pen down
        lines.append(f"G0 Z{pen_down_z:.{dp}f}    ; Pen DOWN")
        pen_is_up = False

        # Draw the path
        for pt in poly[1:]:
            lines.append(
                f"G1 X{pt[0]:.{dp}f} Y{pt[1]:.{dp}f} F{feed_rate:.0f}"
            )

    # ── Footer ────────────────────────────────────────────────────────────────
    lines += [
        "",
        f"G0 Z{pen_up_z:.{dp}f}    ; Final pen UP",
        "G0 X0 Y0     ; Return to origin",
        "M84          ; Disable steppers",
        "; ========================================================",
        "; End of program",
        "; ========================================================",
    ]

    return "\n".join(lines)
