"""
slicer.py
---------
Slices the optimised polylines into layered FDM G-code.

Instead of round-tripping through the STL mesh (which can be slow and lossy),
this slicer works DIRECTLY on the scaled polylines — repeating the same 2D
contours at each Z layer to build up raised extruded traces.

This produces correct, printer-ready Marlin/RepRap G-code with:
  - E-axis extrusion
  - Proper temperatures, fan, retraction
  - Layer-by-layer progression
"""

import math
from typing import List, Tuple, Optional

Point = Tuple[float, float]
Polyline = List[Point]


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

def slice_to_fdm_gcode(
    polylines: List[Polyline],
    layer_height: float = 0.2,          # mm per layer
    trace_height: float = 2.0,          # mm total height of extruded traces
    pen_width: float = 0.5,             # mm line width (= extrusion width)
    filament_diameter: float = 1.75,    # mm
    print_speed: float = 1800,          # mm/min  (30 mm/s)
    travel_speed: float = 6000,         # mm/min (100 mm/s)
    first_layer_speed_factor: float = 0.5,
    hotend_temp: float = 200.0,         # °C
    bed_temp: float = 60.0,             # °C
    retract_length: float = 0.8,        # mm
    retract_speed: float = 2700,        # mm/min (45 mm/s)
    fan_layer: int = 2,                 # Layer to enable part fan
    fan_speed: int = 255,               # 0–255
) -> str:
    """
    Generate FDM G-code from 2D polylines by extruding them layer-by-layer.

    Args:
        polylines      : optimised, bed-scaled polylines in mm
        layer_height   : slice thickness (mm)
        trace_height   : total printed height of the raised traces (mm)
        pen_width      : extrusion line width — affects E calculation

    Returns:
        G-code string (Marlin-compatible, RepRap subset)
    """
    n_layers = max(1, int(trace_height / layer_height))

    # Extrusion volume per mm of travel:
    # E_per_mm = (line_width × layer_height) / (π × (filament_diameter/2)²)
    fil_area    = math.pi * (filament_diameter / 2) ** 2
    e_per_mm    = (pen_width * layer_height) / fil_area

    lines: List[str] = []

    # ── Header / Startup ──────────────────────────────────────────────────────
    lines += [
        "; ============================================================",
        "; FDM Sliced G-code - generated by Image Plotter",
        f"; Layer height    : {layer_height} mm",
        f"; Trace height    : {trace_height} mm  ({n_layers} layers)",
        f"; Line width      : {pen_width} mm",
        f"; Filament        : {filament_diameter} mm",
        f"; Print speed     : {print_speed} mm/min ({print_speed/60:.0f} mm/s)",
        f"; Hotend temp     : {hotend_temp} degC",
        f"; Bed temp        : {bed_temp} degC",
        "; ============================================================",
        "",
        f"M104 S{hotend_temp:.0f}       ; Start heating hotend",
        f"M140 S{bed_temp:.0f}         ; Start heating bed",
        f"M109 S{hotend_temp:.0f}       ; Wait for hotend",
        f"M190 S{bed_temp:.0f}         ; Wait for bed",
        "",
        "G21              ; mm units",
        "G90              ; absolute XYZ positioning",
        "M82              ; absolute E axis",
        "G28              ; home all axes",
        "G92 E0           ; reset extruder",
        "",
        "; ----- Prime line -----",
        "G0 Z0.3 F3000",
        "G0 X5 Y20 F6000",
        "G1 X5 Y120 E8.0 F900   ; prime left edge",
        "G1 X5.4 Y120 F6000",
        "G1 X5.4 Y20 E16.0 F900",
        "G92 E0",
        "",
    ]

    current_e = 0.0
    cur_x, cur_y = 5.0, 20.0

    # ── Layers ────────────────────────────────────────────────────────────────
    for layer_idx in range(n_layers):
        z = (layer_idx + 1) * layer_height
        is_first = (layer_idx == 0)
        speed = int(print_speed * first_layer_speed_factor) if is_first else print_speed

        lines.append(f"; ===== Layer {layer_idx + 1} / {n_layers}  Z={z:.3f} =====")
        lines.append(f"G0 Z{z:.3f} F{travel_speed}")

        if layer_idx + 1 == fan_layer:
            lines.append(f"M106 S{fan_speed}   ; Fan ON at layer {fan_layer}")

        for path_idx, poly in enumerate(polylines):
            if len(poly) < 2:
                continue

            # ── Travel to path start ──────────────────────────────────────────
            sx, sy = poly[0]
            dist = math.hypot(sx - cur_x, sy - cur_y)

            if dist > 0.3:
                # Retract
                current_e -= retract_length
                lines.append(f"G1 E{current_e:.5f} F{retract_speed}  ; retract")
                lines.append(f"G0 X{sx:.3f} Y{sy:.3f} F{travel_speed}  ; travel")
                # Un-retract
                current_e += retract_length
                lines.append(f"G1 E{current_e:.5f} F{retract_speed}  ; un-retract")

            cur_x, cur_y = sx, sy

            # ── Extrude path ──────────────────────────────────────────────────
            for pt in poly[1:]:
                px, py = pt
                seg = math.hypot(px - cur_x, py - cur_y)
                if seg < 0.01:
                    continue
                current_e += seg * e_per_mm
                lines.append(
                    f"G1 X{px:.3f} Y{py:.3f} E{current_e:.5f} F{speed}"
                )
                cur_x, cur_y = px, py

    # ── Footer ────────────────────────────────────────────────────────────────
    final_z = n_layers * layer_height
    lines += [
        "",
        "; ===== End of print =====",
        "M106 S0          ; Fan OFF",
        "M104 S0          ; Hotend OFF",
        "M140 S0          ; Bed OFF",
        f"G0 Z{final_z + 10:.3f} F{travel_speed}  ; Raise Z",
        "G0 X0 Y0         ; Home XY",
        "M84              ; Disable steppers",
        "; ============================================================",
        "; End of sliced G-code",
        "; ============================================================",
    ]

    return "\n".join(lines)


def slicer_stats(polylines: List[Polyline], layer_height: float, trace_height: float):
    """Return a dict of useful slicer statistics."""
    n_layers = max(1, int(trace_height / layer_height))
    total_travel = sum(
        sum(
            math.hypot(poly[i][0] - poly[i-1][0], poly[i][1] - poly[i-1][1])
            for i in range(1, len(poly))
        )
        for poly in polylines
    )
    return {
        "layers": n_layers,
        "layer_height_mm": layer_height,
        "trace_height_mm": trace_height,
        "total_path_length_per_layer_mm": round(total_travel, 1),
        "estimated_total_travel_mm": round(total_travel * n_layers, 1),
    }
